#!/usr/bin/env bash
# The whole m6Anet benchmark, start to finish, on one Ronin instance.
#
#   bash analysis/m6anet/run_ronin.sh setup      # install, ~5 min
#   bash analysis/m6anet/run_ronin.sh convert    # build data.json + index, ~2 min
#   bash analysis/m6anet/run_ronin.sh pretrained # job 1, ~1.5 h
#   bash analysis/m6anet/run_ronin.sh probe      # MEASURE before committing to job 2
#   bash analysis/m6anet/run_ronin.sh retrain    # job 2, hours - read the probe first
#   bash analysis/m6anet/run_ronin.sh score      # results
#
# DO NOT EDIT THIS FILE WHILE IT IS RUNNING. sh reads a script incrementally, so
# an edit mid-run makes the shell resume at the wrong byte offset. This bit us
# twice on the evaluation batch; see analysis/evaluation/run_batch.sh.
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT"

VENV=analysis/m6anet/.venv
M6ANET=$VENV/bin/m6anet
# Everything generated lives under data/, which .gitignore already blocks.
WORK=${M6A_WORK:-data/m6anet}
INPUT=$WORK/input
CVDIR=$WORK/cv
OUT=$WORK/pretrained_out
PY=${PY:-python}

# Data loading dominates: m6Anet opens data.json, seeks and parses JSON once per
# site per epoch. That is CPU and IO, not matrix multiply, so processes matter
# far more than a GPU does. Override if the instance is smaller.
NPROC=${NPROC:-$(nproc)}
EPOCHS=${EPOCHS:-50}
DEVICE=${DEVICE:-cpu}

step=${1:-}

case "$step" in

setup)
    command -v uv >/dev/null 2>&1 || pip install --quiet uv
    uv venv --python 3.8 "$VENV"
    # On Linux the torch==1.6.0 pin usually resolves. If it does not, the
    # --no-deps route below is the one verified to work (torch 2.4.1 is fine;
    # the pin is conservative, not load-bearing).
    uv pip install --python "$VENV" "m6anet==2.1.0" || {
        echo ">> torch 1.6 unavailable here, falling back to the verified route"
        uv pip install --python "$VENV" --no-deps "m6anet==2.1.0"
        uv pip install --python "$VENV" torch "numpy<1.25" pandas scikit-learn \
            toml tqdm setuptools ujson
    }
    "$VENV/bin/python" -c "import m6anet, torch; print('m6anet OK, torch', torch.__version__)"
    ;;

convert)
    $PY analysis/m6anet/make_m6anet_index.py --out "$INPUT"
    echo ">> expect exactly 121,838 sites and 11,027,106 reads. If not, wrong input file."
    ;;

pretrained)
    "$M6ANET" inference --input_dir "$INPUT" --out_dir "$OUT" \
        --pretrained_model HCT116_RNA002 --n_processes "$NPROC"
    echo ">> PULL "$OUT"/data.site_proba.csv OFF THIS INSTANCE."
    ;;

probe)
    # Two epochs on one fold, to turn the retrain cost from a guess into a
    # number BEFORE committing the instance to it. Same discipline the depth
    # and MIL work uses: measure, then decide.
    $PY analysis/m6anet/prepare_cv.py --out "$CVDIR"
    start=$(date +%s)
    "$M6ANET" train --train_config "$CVDIR/fold0/train_config.toml" \
        --save_dir "$CVDIR/fold0/probe" --epochs 2 --save_per_epoch 1 \
        --n_processes "$NPROC" --device "$DEVICE" 2>&1 | tail -6
    each=$(( ($(date +%s) - start) / 2 ))
    echo ""
    echo ">> ~${each}s per epoch on this instance."
    echo ">> 5 folds x ${EPOCHS} epochs = $(( each * EPOCHS * 5 / 3600 )) h."
    echo ">> If that is more than the instance is worth, re-run retrain with"
    echo ">>   EPOCHS=20 bash analysis/m6anet/run_ronin.sh retrain"
    ;;

retrain)
    [ -d "$CVDIR/fold0" ] || $PY analysis/m6anet/prepare_cv.py --out "$CVDIR"
    for fold in 0 1 2 3 4; do
        echo "================ fold $fold: train ================"
        "$M6ANET" train --train_config "$CVDIR/fold$fold/train_config.toml" \
            --save_dir "$CVDIR/fold$fold/run" --epochs "$EPOCHS" \
            --save_per_epoch 5 --n_processes "$NPROC" --device "$DEVICE"
        echo "================ fold $fold: score its held-out sites ================"
        "$M6ANET" inference --input_dir "$CVDIR/fold${fold}_test" \
            --out_dir "$CVDIR/fold${fold}_test/out" \
            --model_state_dict "$CVDIR/fold$fold/run/pr_auc.pt" \
            --n_processes "$NPROC"
    done
    echo ">> PULL $CVDIR/fold*_test/out/data.site_proba.csv OFF THIS INSTANCE."
    ;;

score)
    if [ -f "$OUT"/data.site_proba.csv ]; then
        $PY analysis/m6anet/score_m6anet.py --pretrained "$OUT"/data.site_proba.csv
        echo ""
    fi
    if [ -d "$CVDIR" ]; then
        $PY analysis/m6anet/score_m6anet.py --cv-dir "$CVDIR" \
            --compare analysis/evaluation/reports/final_candidate.json
    fi
    ;;

*)
    sed -n '2,12p' "$0"
    exit 1
    ;;
esac
